// export const COMPLETE_ALL_BIRDS = 'COMPLETE_ALL_BIRDS';
// export const COMPLETE_BIRDS = 'COMPLETE_BIRDS';
export const SET_VISIBILITY_URL = 'SET_VISIBILITY_URL';
export const SET_VISIBILITY_BIRD = 'SET_VISIBILITY_BIRD';
export const SET_ANSWER = 'SET_ANSWER';
export const SET_TRUE_ANSWER = 'SET_TRUE_ANSWER';
